export interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
  difficulty: "easy" | "medium" | "hard";
}

// ── Data Categorization ────────────────────────────────────────────────────────
// Questions designed so that AI / Google gives wrong answers.
// Correct answers follow stated rules, counterintuitive sensitivity hierarchies,
// or careful reading that defeats pattern-matching shortcuts.

const dataCategorization: Question[] = [
  {
    id: "dc1",
    question: "A file named 'billing_2024.xlsx' contains 80% financial billing codes and 20% patient diagnostic notes. Under the PRIMARY SENSITIVITY rule, this file is classified as:",
    options: ["Financial Records", "Healthcare Records", "Billing Data", "Administrative Files"],
    correctAnswer: "Healthcare Records",
    difficulty: "medium",
  },
  {
    id: "dc2",
    question: "A dataset has 1,000 records: 997 are customer emails and 3 are passport scan images. The correct primary classification is:",
    options: ["Customer Communications", "Identity Documents", "Mixed Dataset", "Marketing Data"],
    correctAnswer: "Identity Documents",
    difficulty: "hard",
  },
  {
    id: "dc3",
    question: "Which of the following is NOT a valid reason to escalate a data classification decision?",
    options: ["The file contains data from two equally weighted categories", "The file size exceeds 1 GB", "The data involves a minor's personal information", "The file contains both PII and financial data"],
    correctAnswer: "The file size exceeds 1 GB",
    difficulty: "medium",
  },
  {
    id: "dc4",
    question: "A multi-label document receives these tags: [Financial, PII, Confidential]. When a SINGLE summary label must be displayed, which takes precedence?",
    options: ["Financial", "PII", "Confidential", "All three must always be displayed"],
    correctAnswer: "Confidential",
    difficulty: "hard",
  },
  {
    id: "dc5",
    question: "A PDF contains a tax return on pages 1-10 and the CEO's personal home address on the signature page. The correct classification action is:",
    options: ["Classify as Tax/Financial Records", "Classify as PII only", "Classify as both Financial and PII — PII tag takes priority in the summary label", "Remove the personal address before classifying"],
    correctAnswer: "Classify as both Financial and PII — PII tag takes priority in the summary label",
    difficulty: "hard",
  },
  {
    id: "dc6",
    question: "500 emails are split: 250 marketing, 150 customer support, 100 legal notices. The dataset's primary classification label should be:",
    options: ["Marketing Content", "Mixed Correspondence", "Legal Documents", "Customer Communications"],
    correctAnswer: "Legal Documents",
    difficulty: "hard",
  },
  {
    id: "dc7",
    question: "A file is encrypted and password-protected. The encryption status:",
    options: ["Automatically upgrades the file to 'Confidential' classification", "Does NOT change the file's content-based classification", "Means the file cannot be classified until decrypted", "Reduces classification priority since it is already secured"],
    correctAnswer: "Does NOT change the file's content-based classification",
    difficulty: "medium",
  },
  {
    id: "dc8",
    question: "In batch classification of 1,000 documents, 998 are classified. The 2 unclassified files contain partially redacted medical records. The correct action is:",
    options: ["Leave them unclassified — partial data cannot be classified", "Flag for human expert review before classification", "Default to the most common category in the batch", "Classify as 'Unknown' and proceed"],
    correctAnswer: "Flag for human expert review before classification",
    difficulty: "medium",
  },
  {
    id: "dc9",
    question: "A worker classifies 10 records: 9 correctly and 1 incorrectly. The incorrect record was a healthcare file misclassified as financial. This error type is:",
    options: ["Minor — within acceptable 10% tolerance", "Critical — healthcare misclassification triggers mandatory review", "Standard annotation disagreement", "Acceptable noise in large datasets"],
    correctAnswer: "Critical — healthcare misclassification triggers mandatory review",
    difficulty: "hard",
  },
  {
    id: "dc10",
    question: "'De-identified' medical data (all patient names removed) is classified as:",
    options: ["Public data — no restrictions", "Anonymous data — standard handling", "Still Healthcare Records — sensitivity rules still apply", "Requires reclassification by a medical expert"],
    correctAnswer: "Still Healthcare Records — sensitivity rules still apply",
    difficulty: "hard",
  },
  {
    id: "dc11",
    question: "When classifying social media data, which factor determines the classification FIRST?",
    options: ["The platform where the content was posted", "Whether the content contains PII", "The number of shares the post received", "The date the post was published"],
    correctAnswer: "Whether the content contains PII",
    difficulty: "medium",
  },
  {
    id: "dc12",
    question: "A dataset labeled 'AI Training Data' contains 10,000 fully synthetic AI-generated images with no real people or places. Its sensitivity classification is:",
    options: ["Public / Open Data", "Proprietary AI Assets", "No classification required — synthetic data is unrestricted", "PII-Free — standard data"],
    correctAnswer: "Proprietary AI Assets",
    difficulty: "medium",
  },
  {
    id: "dc13",
    question: "A spreadsheet has columns: Name, Company, Job Title, Work Phone. This dataset is classified as:",
    options: ["PII — personal data requiring protection", "Business Contact Data — generally not PII", "HR Records", "Marketing Data"],
    correctAnswer: "Business Contact Data — generally not PII",
    difficulty: "hard",
  },
  {
    id: "dc14",
    question: "A document has version history showing 5 editors over 2 years. The current version contains only marketing content. Classification is based on:",
    options: ["The CURRENT version's content only", "All historical versions combined", "The version with the most sensitive content", "The original version's content"],
    correctAnswer: "The CURRENT version's content only",
    difficulty: "medium",
  },
  {
    id: "dc15",
    question: "Which data item does NOT require PII handling protocols?",
    options: ["A person's first name only, with no other identifiers", "An email address", "A home address", "A medical record number"],
    correctAnswer: "A person's first name only, with no other identifiers",
    difficulty: "hard",
  },
  {
    id: "dc16",
    question: "An annotation batch has a NULL value in the classification field. According to data quality standards, a NULL classification is:",
    options: ["Acceptable — NULL means the field was intentionally left empty", "The same as an empty string — treat identically", "Always an error requiring mandatory review", "Filled with the most common category in the batch"],
    correctAnswer: "Always an error requiring mandatory review",
    difficulty: "medium",
  },
  {
    id: "dc17",
    question: "Which sequence correctly represents the data classification priority order (highest to lowest)?",
    options: ["PII > Confidential > Internal > Public", "Confidential > PII > Internal > Public", "PII > Internal > Confidential > Public", "Public > Internal > Confidential > PII"],
    correctAnswer: "PII > Confidential > Internal > Public",
    difficulty: "hard",
  },
  {
    id: "dc18",
    question: "An audio recording of a job interview contains the candidate's full name, age, and salary expectations. The PRIMARY classification is:",
    options: ["HR Records", "Audio / Media Files", "PII-Sensitive HR Data", "Recruitment Data"],
    correctAnswer: "PII-Sensitive HR Data",
    difficulty: "medium",
  },
  {
    id: "dc19",
    question: "A company document contains a legal contract (pages 1-10) and an employee performance review (pages 11-15). For classification purposes, you should:",
    options: ["Classify by the content type of the FIRST section only", "Classify as the MOST SENSITIVE content type present", "Classify by the LARGEST section by page count", "Create two separate classification records"],
    correctAnswer: "Classify as the MOST SENSITIVE content type present",
    difficulty: "hard",
  },
  {
    id: "dc20",
    question: "Under data sensitivity hierarchy, which data type ranks LOWEST in classification priority?",
    options: ["Publicly published news articles", "Employee salary records", "Medical diagnosis records", "Government-issued ID scans"],
    correctAnswer: "Publicly published news articles",
    difficulty: "easy",
  },
];

// ── Text Annotation ────────────────────────────────────────────────────────────

const textAnnotation: Question[] = [
  {
    id: "ta1",
    question: "The sentence 'The new policy is not without its merits.' expresses:",
    options: ["Qualified positive sentiment", "Negative sentiment", "Neutral / objective sentiment", "Sarcasm"],
    correctAnswer: "Qualified positive sentiment",
    difficulty: "hard",
  },
  {
    id: "ta2",
    question: "In 'The CEO, who founded the company, resigned yesterday,' the phrase 'who founded the company' is:",
    options: ["A non-restrictive relative clause — can be removed without changing the main meaning", "A restrictive relative clause — essential to identify which CEO", "An appositive phrase", "A conditional clause"],
    correctAnswer: "A non-restrictive relative clause — can be removed without changing the main meaning",
    difficulty: "hard",
  },
  {
    id: "ta3",
    question: "A post reads: 'Wow, the customer service team really outdid themselves... 3 days to answer an email!' The correct annotation is:",
    options: ["Sarcasm — negative sentiment despite positive-sounding words", "Genuine praise — positive feedback about response time", "Neutral observation", "Mixed sentiment — cannot be resolved"],
    correctAnswer: "Sarcasm — negative sentiment despite positive-sounding words",
    difficulty: "medium",
  },
  {
    id: "ta4",
    question: "The sentence 'Not all students who studied failed the exam' means:",
    options: ["Some students who studied passed the exam", "All students who studied passed the exam", "No students who studied failed the exam", "Students who did not study all failed"],
    correctAnswer: "Some students who studied passed the exam",
    difficulty: "hard",
  },
  {
    id: "ta5",
    question: "In aspect-based sentiment analysis, 'The hotel room was spacious but the breakfast was cold' contains:",
    options: ["Two separate aspect sentiments: room=positive, breakfast=negative", "Overall negative sentiment", "Overall positive sentiment with one complaint", "Mixed — cannot be resolved into aspects"],
    correctAnswer: "Two separate aspect sentiments: room=positive, breakfast=negative",
    difficulty: "medium",
  },
  {
    id: "ta6",
    question: "Which sentence is OBJECTIVE (not subjective)?",
    options: ["The study involved 2,400 participants over 18 months.", "The results were surprisingly disappointing.", "The policy seems unnecessarily complicated.", "Many experts believe the approach is flawed."],
    correctAnswer: "The study involved 2,400 participants over 18 months.",
    difficulty: "medium",
  },
  {
    id: "ta7",
    question: "Which annotation correctly labels the relation in: 'SpaceX, owned by Elon Musk, launched a rocket'?",
    options: ["Elon Musk → [OWNS] → SpaceX", "SpaceX → [FOUNDED_BY] → Elon Musk", "Elon Musk → [EMPLOYED_BY] → SpaceX", "SpaceX → [PARTNER_OF] → Elon Musk"],
    correctAnswer: "Elon Musk → [OWNS] → SpaceX",
    difficulty: "hard",
  },
  {
    id: "ta8",
    question: "In part-of-speech tagging, the word 'round' in 'The doctor performed a round of tests' is tagged as:",
    options: ["Noun", "Adjective", "Verb", "Adverb"],
    correctAnswer: "Noun",
    difficulty: "hard",
  },
  {
    id: "ta9",
    question: "Which word in 'The surgery was performed by the experienced surgeon' is the grammatical SUBJECT?",
    options: ["surgery", "surgeon", "The", "performed"],
    correctAnswer: "surgery",
    difficulty: "hard",
  },
  {
    id: "ta10",
    question: "A customer writes: 'I've been a loyal customer for 10 years and this is how you treat me??' The PRIMARY intent label is:",
    options: ["Complaint with implied churn risk", "Praise (mentions loyalty)", "Inquiry (ends with a question)", "Threat"],
    correctAnswer: "Complaint with implied churn risk",
    difficulty: "medium",
  },
  {
    id: "ta11",
    question: "'The White House issued a statement' — 'the White House' should be tagged as:",
    options: ["Organization (U.S. government / executive branch)", "Location (physical building)", "Ambiguous — tag as both", "Person (presidential spokesperson)"],
    correctAnswer: "Organization (U.S. government / executive branch)",
    difficulty: "hard",
  },
  {
    id: "ta12",
    question: "An annotator labels 'The product is okay, I guess.' as Neutral. This annotation is:",
    options: ["Incorrect — 'okay, I guess' signals weak negative sentiment", "Correct — 'okay' is a neutral term", "Correct — 'I guess' indicates uncertainty, not sentiment", "Incorrect — 'okay' is positive"],
    correctAnswer: "Incorrect — 'okay, I guess' signals weak negative sentiment",
    difficulty: "hard",
  },
  {
    id: "ta13",
    question: "In temporal expression labeling, 'next Friday' in a document written on a Thursday evening refers to:",
    options: ["The Friday immediately following — i.e., tomorrow", "The Friday of the following week", "Ambiguous — requires document metadata", "The nearest future Friday regardless of day"],
    correctAnswer: "The Friday immediately following — i.e., tomorrow",
    difficulty: "hard",
  },
  {
    id: "ta14",
    question: "A hate speech classifier must label: 'People from X country are always late.' This is:",
    options: ["Stereotyping / Mild Bias — flagged but not hate speech", "Clear hate speech — direct attack on a group", "Neutral observation — a statistical statement", "Sarcasm"],
    correctAnswer: "Stereotyping / Mild Bias — flagged but not hate speech",
    difficulty: "hard",
  },
  {
    id: "ta15",
    question: "In a sentence annotation exercise, underline all VERBS. In 'Swimming is her favorite activity,' the verb is:",
    options: ["is", "Swimming", "favorite", "activity"],
    correctAnswer: "is",
    difficulty: "hard",
  },
  {
    id: "ta16",
    question: "The phrase 'The battery is great BUT the camera is terrible' — the word BUT serves as:",
    options: ["Contrastive conjunction", "Causal conjunction", "Temporal reference", "Conditional marker"],
    correctAnswer: "Contrastive conjunction",
    difficulty: "easy",
  },
  {
    id: "ta17",
    question: "'The bank raised its interest rates. It also announced new fees.' — 'It' in the second sentence refers to:",
    options: ["The bank", "The interest rates", "Ambiguous — could be either", "A different institution"],
    correctAnswer: "The bank",
    difficulty: "medium",
  },
  {
    id: "ta18",
    question: "In named entity recognition, 'Mars' in a space-science article most likely refers to:",
    options: ["The planet Mars", "The Mars chocolate brand", "A person named Mars", "A city on Earth"],
    correctAnswer: "The planet Mars",
    difficulty: "medium",
  },
  {
    id: "ta19",
    question: "Identify the sentence type: 'If it rains tomorrow, we should cancel the outdoor event.'",
    options: ["Conditional", "Declarative", "Interrogative", "Exclamatory"],
    correctAnswer: "Conditional",
    difficulty: "easy",
  },
  {
    id: "ta20",
    question: "In 'John flew from New York to Paris', how many LOCATION entities are present?",
    options: ["2", "1", "3", "0"],
    correctAnswer: "2",
    difficulty: "easy",
  },
];

// ── Questionnaires ─────────────────────────────────────────────────────────────

const questionnaires: Question[] = [
  {
    id: "qu1",
    question: "Survey question: 'How much do you enjoy our excellent customer service?' This is an example of:",
    options: ["Leading question", "Double-barreled question", "Loaded question", "Hypothetical question"],
    correctAnswer: "Leading question",
    difficulty: "medium",
  },
  {
    id: "qu2",
    question: "A researcher removes the 'Neutral' option from a 5-point Likert scale. This creates:",
    options: ["A forced-choice scale — respondents must take a position", "An invalid scale — Neutral is always required", "A biased scale that inflates positive responses", "A semantic differential scale"],
    correctAnswer: "A forced-choice scale — respondents must take a position",
    difficulty: "hard",
  },
  {
    id: "qu3",
    question: "Survey question: 'Do you exercise regularly and eat healthy?' This violates which design principle?",
    options: ["Double-barreled question — asks two things at once", "Leading question — implies you should do both", "Loaded question — assumes prior behavior", "Ambiguous question — 'regularly' is undefined"],
    correctAnswer: "Double-barreled question — asks two things at once",
    difficulty: "medium",
  },
  {
    id: "qu4",
    question: "A phone survey finds 70% response rate among people 65+ but only 15% among people 18-34. This most likely introduces:",
    options: ["Coverage bias — certain groups are systematically underrepresented", "Acquiescence bias", "Social desirability bias", "Recall bias"],
    correctAnswer: "Coverage bias — certain groups are systematically underrepresented",
    difficulty: "hard",
  },
  {
    id: "qu5",
    question: "A respondent answers: Strongly Agree, Strongly Agree, Strongly Agree, Strongly Agree, Strongly Agree for 5 unrelated statements. This most likely indicates:",
    options: ["Acquiescence bias (yes-saying)", "Genuine strong agreement with all statements", "Social desirability bias", "Extreme response style"],
    correctAnswer: "Acquiescence bias (yes-saying)",
    difficulty: "hard",
  },
  {
    id: "qu6",
    question: "Response rate for a sensitive income question is highest when the question is placed:",
    options: ["At the END of the survey", "At the START of the survey", "In the MIDDLE of the survey", "Placement does not affect response rate"],
    correctAnswer: "At the END of the survey",
    difficulty: "hard",
  },
  {
    id: "qu7",
    question: "An NPS survey asks: 'How likely are you to recommend us? (0-10)' Scores of 7 and 8 are classified as:",
    options: ["Passives — neither detractors nor promoters", "Promoters", "Detractors", "Neutrals — excluded from NPS calculation"],
    correctAnswer: "Passives — neither detractors nor promoters",
    difficulty: "hard",
  },
  {
    id: "qu8",
    question: "A survey is administered to ALL employees of a company. This is best described as:",
    options: ["A census — no sampling method applies", "Convenience sampling", "Purposive sampling", "Systematic sampling"],
    correctAnswer: "A census — no sampling method applies",
    difficulty: "hard",
  },
  {
    id: "qu9",
    question: "Survey question: 'Some people believe vaccines cause harm. Do you think vaccines are safe?' This introduces:",
    options: ["Framing bias — the opening statement primes respondents toward doubt", "Leading question — directly asks for a specific answer", "Social desirability bias", "Acquiescence bias"],
    correctAnswer: "Framing bias — the opening statement primes respondents toward doubt",
    difficulty: "hard",
  },
  {
    id: "qu10",
    question: "Which of the following is NOT a recognized type of survey validity?",
    options: ["Computational validity", "Content validity", "Construct validity", "Criterion validity"],
    correctAnswer: "Computational validity",
    difficulty: "hard",
  },
  {
    id: "qu11",
    question: "In an online survey, 40% of respondents drop off after question 3 of 20. The most likely cause is:",
    options: ["Question 3 is too complex, sensitive, or long", "The survey platform has a technical error", "Respondents are not interested in the topic", "The survey rewards are insufficient"],
    correctAnswer: "Question 3 is too complex, sensitive, or long",
    difficulty: "medium",
  },
  {
    id: "qu12",
    question: "Social desirability bias in surveys causes respondents to:",
    options: ["Answer in ways they think will be viewed favorably, not truthfully", "Agree with all statements regardless of content", "Only answer questions they feel strongly about", "Skip sensitive questions entirely"],
    correctAnswer: "Answer in ways they think will be viewed favorably, not truthfully",
    difficulty: "easy",
  },
  {
    id: "qu13",
    question: "Test-retest reliability means:",
    options: ["The same respondents give similar answers when asked the same questions at different times", "Different respondents give similar answers to the same questions", "The survey measures what it claims to measure", "The survey produces consistent factor loadings"],
    correctAnswer: "The same respondents give similar answers when asked the same questions at different times",
    difficulty: "medium",
  },
  {
    id: "qu14",
    question: "A survey question: 'Wouldn't you agree that our new app is better than the old one?' has how many distinct problems?",
    options: ["Two — it is both a leading question AND uses a negative phrasing ('Wouldn't')", "One — it is only a leading question", "One — it only uses negative phrasing", "None — comparing products is a standard survey technique"],
    correctAnswer: "Two — it is both a leading question AND uses a negative phrasing ('Wouldn't')",
    difficulty: "hard",
  },
  {
    id: "qu15",
    question: "A respondent who has never used the product selects 'N/A' for 'Rate your satisfaction with our product.' This response should be:",
    options: ["Excluded from satisfaction analysis — N/A is not a satisfaction rating", "Treated as the neutral midpoint", "Treated as missing data and imputed", "Treated as a negative response"],
    correctAnswer: "Excluded from satisfaction analysis — N/A is not a satisfaction rating",
    difficulty: "hard",
  },
  {
    id: "qu16",
    question: "A survey is administered by the manager to their own team. This introduces:",
    options: ["Both interviewer effect AND social desirability bias", "Only social desirability bias", "Only coverage bias", "No bias — managers can survey their teams"],
    correctAnswer: "Both interviewer effect AND social desirability bias",
    difficulty: "hard",
  },
  {
    id: "qu17",
    question: "A survey translated from English is back-translated to English to check for meaning drift. This technique is called:",
    options: ["Back-translation verification", "Linguistic equivalence testing", "Construct replication", "Semantic differential testing"],
    correctAnswer: "Back-translation verification",
    difficulty: "medium",
  },
  {
    id: "qu18",
    question: "To ensure equal representation of all age groups in a population survey, you should use:",
    options: ["Stratified random sampling", "Simple random sampling", "Cluster sampling", "Systematic sampling"],
    correctAnswer: "Stratified random sampling",
    difficulty: "easy",
  },
  {
    id: "qu19",
    question: "A 10-question survey has an average completion time of 4 minutes. This most likely suggests:",
    options: ["Many respondents are not reading questions carefully (speeding)", "The survey is efficiently designed", "4 minutes per question is normal", "The questions are too simple"],
    correctAnswer: "Many respondents are not reading questions carefully (speeding)",
    difficulty: "hard",
  },
  {
    id: "qu20",
    question: "A 7-point scale (1=Very Bad to 7=Very Good) is used. A score of 4 represents:",
    options: ["The neutral midpoint — neither good nor bad", "A slightly negative response", "A slightly positive response", "Cannot be interpreted without the distribution"],
    correctAnswer: "The neutral midpoint — neither good nor bad",
    difficulty: "easy",
  },
];

// ── AI Training Tasks ──────────────────────────────────────────────────────────

const aiTrainingTasks: Question[] = [
  {
    id: "ai1",
    question: "A model trained on 9,500 cat images and 500 dog images achieves 96% accuracy. This result is:",
    options: ["Misleading — the model likely just predicts 'cat' for everything", "Excellent — 96% is a strong result", "Unacceptable — below industry benchmark", "Valid — the imbalance is not severe enough to matter"],
    correctAnswer: "Misleading — the model likely just predicts 'cat' for everything",
    difficulty: "hard",
  },
  {
    id: "ai2",
    question: "In RLHF (Reinforcement Learning from Human Feedback), human annotators are primarily asked to:",
    options: ["Rank or compare model outputs by quality — not just label right/wrong", "Write new training examples from scratch", "Label only factual accuracy of model responses", "Test model outputs for safety violations exclusively"],
    correctAnswer: "Rank or compare model outputs by quality — not just label right/wrong",
    difficulty: "hard",
  },
  {
    id: "ai3",
    question: "A training dataset for medical diagnosis AI has all records from one hospital. This creates primary risk of:",
    options: ["Distribution shift — the model may not generalize to other hospitals", "Overfitting to the specific training records", "Class imbalance in disease categories", "Insufficient volume for deep learning"],
    correctAnswer: "Distribution shift — the model may not generalize to other hospitals",
    difficulty: "hard",
  },
  {
    id: "ai4",
    question: "In a spam classifier, which mislabeling causes the MOST damage?",
    options: ["Labeling a legitimate email as spam (False Positive)", "Labeling a spam email as legitimate (False Negative)", "Both are equally damaging", "Neither — spam classifiers are robust to label noise"],
    correctAnswer: "Labeling a legitimate email as spam (False Positive)",
    difficulty: "hard",
  },
  {
    id: "ai5",
    question: "An annotation guideline states: 'Bounding boxes must be TIGHT — include the minimum pixels containing the object.' An annotator adds 5% extra padding. This annotation is:",
    options: ["Incorrect — the guideline explicitly requires tight boxes", "Acceptable — minor padding is standard practice", "Preferred — padding prevents edge clipping", "Neutral — padding does not affect training"],
    correctAnswer: "Incorrect — the guideline explicitly requires tight boxes",
    difficulty: "hard",
  },
  {
    id: "ai6",
    question: "Inter-annotator agreement (Cohen's Kappa) of 0.4 indicates:",
    options: ["Moderate agreement — borderline acceptable, guideline review recommended", "High agreement — exceeds standard thresholds", "Poor agreement — project should be halted immediately", "Chance agreement — no real consensus"],
    correctAnswer: "Moderate agreement — borderline acceptable, guideline review recommended",
    difficulty: "hard",
  },
  {
    id: "ai7",
    question: "In object detection, a partially hidden car (30% occluded by a truck) should be annotated with:",
    options: ["A bounding box covering the FULL estimated extent of the car, including the occluded portion", "A bounding box only around the visible 70%", "No annotation — occlusion above 20% means skip", "A point marker at the visible center"],
    correctAnswer: "A bounding box covering the FULL estimated extent of the car, including the occluded portion",
    difficulty: "hard",
  },
  {
    id: "ai8",
    question: "A model flags offensive language correctly 99% of the time but NEVER detects subtle coded hate speech. This means:",
    options: ["The test set does not represent real-world distribution — a capability gap exists", "The model is performing correctly — coded speech is not offensive language", "99% accuracy is insufficient for hate speech detection", "The model needs more training data in general"],
    correctAnswer: "The test set does not represent real-world distribution — a capability gap exists",
    difficulty: "hard",
  },
  {
    id: "ai9",
    question: "The correct order for creating a supervised ML training dataset is:",
    options: ["Define task → Create guidelines → Annotate → Review → Train", "Collect data → Annotate → Define task → Train → Review", "Annotate → Review → Define task → Collect data → Train", "Define task → Collect data → Train → Annotate → Review"],
    correctAnswer: "Define task → Create guidelines → Annotate → Review → Train",
    difficulty: "medium",
  },
  {
    id: "ai10",
    question: "1,000 sentiment reviews include 50 sarcastic ones. A model correctly labels all 950 non-sarcastic reviews but fails on ALL 50 sarcastic ones. Reported accuracy is:",
    options: ["95% — but sarcasm detection is completely absent (zero recall on that class)", "95% — acceptable overall performance", "90% — adjusted for the sarcasm failure", "Cannot be calculated without more information"],
    correctAnswer: "95% — but sarcasm detection is completely absent (zero recall on that class)",
    difficulty: "hard",
  },
  {
    id: "ai11",
    question: "In semantic segmentation, a car's shadow in the image should be labeled as:",
    options: ["Background / ground — the shadow is not part of the car", "Car — the shadow is caused by the car", "Ambiguous — flag for review", "A separate 'shadow' class"],
    correctAnswer: "Background / ground — the shadow is not part of the car",
    difficulty: "hard",
  },
  {
    id: "ai12",
    question: "In NLP model training, 'tokenization' refers to:",
    options: ["Splitting text into individual units (words, subwords, or characters) for processing", "Removing stopwords from the training corpus", "Encoding text as numerical vectors", "Labeling parts of speech in training data"],
    correctAnswer: "Splitting text into individual units (words, subwords, or characters) for processing",
    difficulty: "easy",
  },
  {
    id: "ai13",
    question: "Transfer learning is MOST beneficial when:",
    options: ["The new task has limited labeled data but is related to the pre-trained model's domain", "The new task has thousands of labeled examples", "The new task is completely different from the pre-trained domain", "The pre-trained model achieves 100% on its original task"],
    correctAnswer: "The new task has limited labeled data but is related to the pre-trained model's domain",
    difficulty: "medium",
  },
  {
    id: "ai14",
    question: "A language model trained on 80% English and 20% other languages will likely:",
    options: ["Perform significantly better in English than in other languages", "Perform equally across all languages if properly fine-tuned", "Fail entirely on non-English inputs", "Show no language performance difference — transformers are language-agnostic"],
    correctAnswer: "Perform significantly better in English than in other languages",
    difficulty: "medium",
  },
  {
    id: "ai15",
    question: "An annotation project has the same 200 sentences given to all 3 annotators. The 200 shared sentences are used to:",
    options: ["Calculate inter-annotator agreement and calibrate annotator quality", "Serve as additional training examples", "Validate the annotation tool's accuracy", "Reduce overall annotation cost"],
    correctAnswer: "Calculate inter-annotator agreement and calibrate annotator quality",
    difficulty: "medium",
  },
  {
    id: "ai16",
    question: "A text classification model has F1=0.90 for Positive, F1=0.88 for Negative, but F1=0.35 for Neutral. The correct action is:",
    options: ["Improve Neutral class training data — it is critically underperforming", "Report macro-average F1 and consider the model acceptable", "Remove the Neutral class — it's too difficult to classify", "Accept the model — average F1 across classes may still be acceptable"],
    correctAnswer: "Improve Neutral class training data — it is critically underperforming",
    difficulty: "hard",
  },
  {
    id: "ai17",
    question: "In named entity recognition, 'John F. Kennedy Airport' should be labeled as:",
    options: ["LOCATION (FAC — facility/infrastructure)", "PERSON (contains a person's name)", "ORG (named after a person = organization)", "Ambiguous — split into PERSON + LOCATION"],
    correctAnswer: "LOCATION (FAC — facility/infrastructure)",
    difficulty: "hard",
  },
  {
    id: "ai18",
    question: "A 10,000/10,000 train/test split yields 95% accuracy. A reviewer should first ask:",
    options: ["Whether the test set was used during hyperparameter tuning (data leakage risk)", "Why the test set equals the training set in size", "Whether 10,000 test examples are statistically sufficient", "Whether 95% meets the minimum benchmark for this domain"],
    correctAnswer: "Whether the test set was used during hyperparameter tuning (data leakage risk)",
    difficulty: "hard",
  },
  {
    id: "ai19",
    question: "Active learning in machine learning means the model:",
    options: ["Queries for labels on the data points it is MOST uncertain about", "Trains continuously on all new incoming data", "Is monitored by human trainers during every training step", "Learns from reinforcement without any labeled data"],
    correctAnswer: "Queries for labels on the data points it is MOST uncertain about",
    difficulty: "medium",
  },
  {
    id: "ai20",
    question: "When two annotators label the same record differently, the correct resolution is:",
    options: ["Apply the annotation guidelines and escalate to adjudication if still ambiguous", "Always prefer the more experienced annotator's label", "Use the label that appears most frequently across all annotators", "Discard the example — disagreement means it is unusable"],
    correctAnswer: "Apply the annotation guidelines and escalate to adjudication if still ambiguous",
    difficulty: "medium",
  },
];

// ── Sentence Arrangement ───────────────────────────────────────────────────────

const sentenceArrangement: Question[] = [
  {
    id: "sa1",
    question: "Arrange these 4 sentences in correct logical order:\n(W) Therefore, road maintenance budgets must be increased.\n(X) Heavy rainfall causes significant road surface damage.\n(Y) Damaged roads lead to increased vehicle repair costs.\n(Z) Vehicle repair costs burden both individuals and the economy.\nThe correct sequence is:",
    options: ["X → Y → Z → W", "W → X → Y → Z", "X → W → Y → Z", "Y → X → Z → W"],
    correctAnswer: "X → Y → Z → W",
    difficulty: "medium",
  },
  {
    id: "sa2",
    question: "The sentence 'Having eaten the entire cake, the birthday party was ruined.' is an example of:",
    options: ["A dangling modifier — 'having eaten' incorrectly modifies 'the birthday party'", "A correctly structured participial phrase", "A passive voice construction", "An absolute phrase"],
    correctAnswer: "A dangling modifier — 'having eaten' incorrectly modifies 'the birthday party'",
    difficulty: "hard",
  },
  {
    id: "sa3",
    question: "In persuasive writing, the WEAKEST argument should be placed:",
    options: ["In the MIDDLE — sandwiched between stronger arguments", "At the START — to establish baseline credibility", "At the END — so the audience discounts it least", "Weakest arguments should always be omitted"],
    correctAnswer: "In the MIDDLE — sandwiched between stronger arguments",
    difficulty: "hard",
  },
  {
    id: "sa4",
    question: "In SWOT analysis, the conventional presentation order is:",
    options: ["Strengths → Weaknesses → Opportunities → Threats", "Strengths → Opportunities → Weaknesses → Threats", "Opportunities → Threats → Strengths → Weaknesses", "Weaknesses → Strengths → Threats → Opportunities"],
    correctAnswer: "Strengths → Weaknesses → Opportunities → Threats",
    difficulty: "easy",
  },
  {
    id: "sa5",
    question: "To combine 'The report was not approved.' and 'It contained several errors.' using a CAUSAL connector, you write:",
    options: ["'The report was not approved because it contained several errors.'", "'The report was not approved, however it contained several errors.'", "'The report was not approved, therefore it contained several errors.'", "'The report was not approved, similarly it contained several errors.'"],
    correctAnswer: "'The report was not approved because it contained several errors.'",
    difficulty: "medium",
  },
  {
    id: "sa6",
    question: "Which sentence uses parallel structure CORRECTLY?",
    options: ["She likes running, swimming, and hiking.", "She likes running, to swim, and hiking.", "She likes to run, swimming, and hikes.", "She likes run, swim, and hike."],
    correctAnswer: "She likes running, swimming, and hiking.",
    difficulty: "easy",
  },
  {
    id: "sa7",
    question: "The correct sentence regarding subject-verb agreement is:",
    options: ["Neither John nor his colleagues were present.", "Neither John nor his colleagues was present.", "Neither John nor his colleagues are present.", "Neither John or his colleagues were present."],
    correctAnswer: "Neither John nor his colleagues were present.",
    difficulty: "hard",
  },
  {
    id: "sa8",
    question: "A news article's inverted pyramid structure places information in this order:",
    options: ["Most important facts first, then supporting details, then background", "Background first, then details, then key facts", "Chronological order — oldest events first", "Equal importance throughout — no hierarchy"],
    correctAnswer: "Most important facts first, then supporting details, then background",
    difficulty: "medium",
  },
  {
    id: "sa9",
    question: "In a research paper using IMRaD structure, the 'Discussion' section should:",
    options: ["Interpret results in context of prior literature — NOT introduce new data", "Present the raw data collected", "Describe the methodology used", "List all references cited"],
    correctAnswer: "Interpret results in context of prior literature — NOT introduce new data",
    difficulty: "medium",
  },
  {
    id: "sa10",
    question: "Sentence: 'The data shows that sales increased by 15%, which proves our strategy works.' The logical error is:",
    options: ["Both hasty generalization AND correlation/causation confusion", "No error — a 15% increase is sufficient evidence", "Only correlation vs. causation confusion", "Only hasty generalization"],
    correctAnswer: "Both hasty generalization AND correlation/causation confusion",
    difficulty: "hard",
  },
  {
    id: "sa11",
    question: "Which demonstrates INCORRECT use of a semicolon?",
    options: ["I enjoy cooking; pasta, pizza, and risotto.", "I went to the store; I bought milk.", "She studied hard; however, she failed.", "The results were inconclusive; further research is needed."],
    correctAnswer: "I enjoy cooking; pasta, pizza, and risotto.",
    difficulty: "hard",
  },
  {
    id: "sa12",
    question: "A procedural recipe has steps: (A) Allow to cool. (B) Preheat oven to 180°C. (C) Mix ingredients. (D) Bake 30 minutes. (E) Serve. The correct sequence is:",
    options: ["B → C → D → A → E", "C → B → D → A → E", "B → D → C → A → E", "C → D → B → A → E"],
    correctAnswer: "B → C → D → A → E",
    difficulty: "medium",
  },
  {
    id: "sa13",
    question: "A legal document must present clauses in order: Definitions → Rights → Obligations → Remedies → Termination. Placing 'Remedies' before 'Obligations' is:",
    options: ["Incorrectly structured — remedies must follow the obligations they address", "Acceptable — clause order in legal documents is flexible", "Only an issue if the contract is disputed", "Correct — remedies are more important than obligations"],
    correctAnswer: "Incorrectly structured — remedies must follow the obligations they address",
    difficulty: "hard",
  },
  {
    id: "sa14",
    question: "In formal professional email writing, which component ALWAYS appears last?",
    options: ["Closing salutation (e.g., 'Best regards, [Name]')", "Subject line", "Main body content", "Opening greeting"],
    correctAnswer: "Closing salutation (e.g., 'Best regards, [Name]')",
    difficulty: "easy",
  },
  {
    id: "sa15",
    question: "Which transition word BEST connects a contrast between two ideas?",
    options: ["However", "Furthermore", "Therefore", "Similarly"],
    correctAnswer: "However",
    difficulty: "easy",
  },
  {
    id: "sa16",
    question: "'The surgery was performed by the experienced surgeon' — 'surgery' is the:",
    options: ["Grammatical subject (passive construction)", "Object of the sentence", "Predicate noun", "Indirect object"],
    correctAnswer: "Grammatical subject (passive construction)",
    difficulty: "hard",
  },
  {
    id: "sa17",
    question: "A paragraph ends: '...and that is why solar energy is the future.' This sentence functions as:",
    options: ["A concluding sentence that restates the main point", "A topic sentence introducing a new idea", "A transition sentence to the next paragraph", "Evidence supporting an argument"],
    correctAnswer: "A concluding sentence that restates the main point",
    difficulty: "easy",
  },
  {
    id: "sa18",
    question: "In the sentence 'Time flies like an arrow; fruit flies like a banana,' the reason this is famous in linguistics is:",
    options: ["It demonstrates syntactic ambiguity — 'flies' and 'like' can be parsed differently in each clause", "It is a metaphor about time and fruit", "It shows how punctuation changes meaning", "It is a canonical example of a compound sentence"],
    correctAnswer: "It demonstrates syntactic ambiguity — 'flies' and 'like' can be parsed differently in each clause",
    difficulty: "hard",
  },
  {
    id: "sa19",
    question: "A footnote in a formal report is used to:",
    options: ["Provide supplementary information without interrupting the main text", "Replace in-text citations entirely", "List all references used in the report", "Explain the research methodology"],
    correctAnswer: "Provide supplementary information without interrupting the main text",
    difficulty: "easy",
  },
  {
    id: "sa20",
    question: "A strictly chronological company history narrative should begin with:",
    options: ["The earliest event in the company's history", "The company's current achievements (hook)", "The founding moment as the climax", "A problem the company solved (conflict setup)"],
    correctAnswer: "The earliest event in the company's history",
    difficulty: "medium",
  },
];

// ── Product Review Analysis ────────────────────────────────────────────────────

const productReviewAnalysis: Question[] = [
  {
    id: "pr1",
    question: "A review reads: 'Five stars! This product literally saved my life!!!! Will buy again.' This should be flagged as:",
    options: ["Potentially inauthentic — excessive enthusiasm with no specific details", "A genuine high-quality review", "Sarcasm — 'saved my life' signals irony", "Too short to analyze"],
    correctAnswer: "Potentially inauthentic — excessive enthusiasm with no specific details",
    difficulty: "medium",
  },
  {
    id: "pr2",
    question: "A product has 1,000 reviews averaging 4.2 stars overall. The 50 most recent reviews average 2.1 stars. The BEST interpretation is:",
    options: ["Product quality may have declined — recent reviews are more relevant", "The 4.2 average is more reliable due to larger sample size", "The recent reviews are likely a coordinated attack", "Both ratings are equally informative"],
    correctAnswer: "Product quality may have declined — recent reviews are more relevant",
    difficulty: "hard",
  },
  {
    id: "pr3",
    question: "A reviewer writes: 'I've never used this product but based on the ingredients it seems dangerous.' This review should be:",
    options: ["Removed — the reviewer has no verified experience with the product", "Kept — ingredient warnings are valuable consumer information", "Flagged for expert verification before publication", "Moved to a Q&A section"],
    correctAnswer: "Removed — the reviewer has no verified experience with the product",
    difficulty: "medium",
  },
  {
    id: "pr4",
    question: "A product page has 200 reviews: 180 are 5-star, 15 are 1-star, and 5 are 3-star. There are NO 2-star or 4-star reviews. This distribution suggests:",
    options: ["Potential review manipulation — natural reviews rarely show this bimodal pattern", "The product is genuinely polarizing among buyers", "Excellent product — 90% 5-star is strong", "No issue — unusual distributions can occur naturally"],
    correctAnswer: "Potential review manipulation — natural reviews rarely show this bimodal pattern",
    difficulty: "hard",
  },
  {
    id: "pr5",
    question: "A review reads: 'Great product, received it for free in exchange for my honest review.' According to FTC guidelines, this review:",
    options: ["Can remain — the disclosure is visible, qualifying it as a labeled incentivized review", "Must be removed — incentivized reviews are always prohibited", "Must be hidden pending investigation", "Requires no action — all reviews are treated equally"],
    correctAnswer: "Can remain — the disclosure is visible, qualifying it as a labeled incentivized review",
    difficulty: "hard",
  },
  {
    id: "pr6",
    question: "A verified purchaser gives 5 stars but writes: 'delivery took 3 weeks and customer service ignored me.' This review should be:",
    options: ["Flagged — the text contradicts the star rating, requiring moderation review", "Published as-is — the star rating takes priority for aggregate calculations", "Treated as a 1-star review based on the text content", "No action — users can rate however they choose"],
    correctAnswer: "Flagged — the text contradicts the star rating, requiring moderation review",
    difficulty: "hard",
  },
  {
    id: "pr7",
    question: "50 identical one-star reviews with similar phrasing appear within 24 hours. This is:",
    options: ["Review bombing — coordinated inauthentic activity that should be removed", "A valid spike of negative customer experience", "Suspicious but not actionable without more evidence", "A competitive marketing technique that is common practice"],
    correctAnswer: "Review bombing — coordinated inauthentic activity that should be removed",
    difficulty: "medium",
  },
  {
    id: "pr8",
    question: "A review for a children's toy reads: 'My 3-year-old loved it but swallowed a small part within the first day.' This review should:",
    options: ["Be flagged as a safety report — requires urgent escalation beyond standard moderation", "Be removed — it describes product misuse", "Be kept as-is — it's an honest consumer experience", "Be edited to remove the swallowing incident before publishing"],
    correctAnswer: "Be flagged as a safety report — requires urgent escalation beyond standard moderation",
    difficulty: "hard",
  },
  {
    id: "pr9",
    question: "A seller responds to a 1-star review: 'This reviewer is lying. They never purchased this product.' The seller's response:",
    options: ["Violates platform guidelines — aggressive responses are prohibited", "Is helpful — defending against false reviews is appropriate", "Should trigger an investigation into the reviewer", "Is acceptable if the seller can prove no purchase was made"],
    correctAnswer: "Violates platform guidelines — aggressive responses are prohibited",
    difficulty: "medium",
  },
  {
    id: "pr10",
    question: "A verified purchaser leaves a 1-star review 6 months after purchase: 'It broke after 5 months of normal use.' The platform should:",
    options: ["Keep the review — durability is a relevant product quality attribute", "Remove it — post-warranty reviews are irrelevant to current buyers", "Flag it — 5-month timeframe is beyond typical review validity", "Ask the reviewer to contact support instead"],
    correctAnswer: "Keep the review — durability is a relevant product quality attribute",
    difficulty: "medium",
  },
  {
    id: "pr11",
    question: "Which review metric is MOST useful for detecting paid review manipulation?",
    options: ["Velocity of review submissions (many reviews in a short period)", "Average star rating across all reviews", "Total number of reviews", "Percentage of verified purchase reviews"],
    correctAnswer: "Velocity of review submissions (many reviews in a short period)",
    difficulty: "hard",
  },
  {
    id: "pr12",
    question: "Which of the following is a sign of an AUTHENTIC review?",
    options: ["Mentions a specific problem encountered and how it was resolved", "Uses superlatives repeatedly: 'Best product ever, absolutely amazing!'", "Was posted within 24 hours of purchase", "Contains the exact same phrases as 5 other reviews"],
    correctAnswer: "Mentions a specific problem encountered and how it was resolved",
    difficulty: "medium",
  },
  {
    id: "pr13",
    question: "100 reviews mention 'the smell is strong.' 90 say the smell is positive; 10 say it's negative. For product listing purposes, this data should be:",
    options: ["Listed as a notable product attribute — smell is a differentiating feature", "Ignored — subjective sensory feedback is not useful", "Added as a warning: 'Strong smell — may not suit all users'", "Treated as negative since 10% report it negatively"],
    correctAnswer: "Listed as a notable product attribute — smell is a differentiating feature",
    difficulty: "hard",
  },
  {
    id: "pr14",
    question: "A review contains: 'Great product! Check out [competitor website] for similar items!' This review should be:",
    options: ["Removed — contains competitor promotion / spam", "Kept — the reviewer is sharing useful information", "Edited to remove the URL only", "Flagged for brand safety review"],
    correctAnswer: "Removed — contains competitor promotion / spam",
    difficulty: "medium",
  },
  {
    id: "pr15",
    question: "An annotator's task is to label reviews as 'Actionable' or 'Non-Actionable' for product improvement. Which review is 'Actionable'?",
    options: ["'The charging cable could be 50cm longer — it barely reaches my bedside.'", "'I love this product, it's great!'", "'Arrived on time, works as described.'", "'I ordered the wrong color, that was my mistake.'"],
    correctAnswer: "'The charging cable could be 50cm longer — it barely reaches my bedside.'",
    difficulty: "medium",
  },
  {
    id: "pr16",
    question: "A product review says: 'This is exactly what the description said it would be.' The review sentiment is:",
    options: ["Positive — meeting described expectations is a successful outcome", "Neutral — simply confirms product match, no opinion expressed", "Not useful — adds no new information beyond the listing", "Negative — implies expectations were low"],
    correctAnswer: "Positive — meeting described expectations is a successful outcome",
    difficulty: "hard",
  },
  {
    id: "pr17",
    question: "A researcher randomly samples 100 reviews from 10,000 for sentiment analysis. The results show 75% positive. The correct conclusion is:",
    options: ["The sample likely represents the full population if randomly selected", "100 reviews is too small to represent 10,000", "Random sampling of reviews introduces selection bias", "The analysis should use all 10,000 reviews for accuracy"],
    correctAnswer: "The sample likely represents the full population if randomly selected",
    difficulty: "hard",
  },
  {
    id: "pr18",
    question: "A restaurant review rates 5 stars and writes: 'The ambiance was fantastic but food was inedible and service was rude.' For sentiment analysis, the OVERALL sentiment is:",
    options: ["Mixed — multiple conflicting aspects present", "Positive — 5 stars is the definitive sentiment signal", "Negative — food and service are the core product attributes", "Cannot be determined"],
    correctAnswer: "Mixed — multiple conflicting aspects present",
    difficulty: "medium",
  },
  {
    id: "pr19",
    question: "A 1-star review says only: 'Arrived damaged.' This review is:",
    options: ["Valid — shipping damage is a legitimate product/fulfillment issue", "Invalid — shipping damage is not the seller's fault", "Incomplete — insufficient detail to publish", "A logistics complaint, not a product review — should be removed"],
    correctAnswer: "Valid — shipping damage is a legitimate product/fulfillment issue",
    difficulty: "medium",
  },
  {
    id: "pr20",
    question: "A review written in Spanish on an English-language product page should be:",
    options: ["Kept — multilingual reviews are valid and help other speakers", "Removed — English-only reviews are required for this market", "Machine-translated before publication", "Hidden by default with a 'Show translation' option only"],
    correctAnswer: "Kept — multilingual reviews are valid and help other speakers",
    difficulty: "medium",
  },
];

// ── Data Annotation ────────────────────────────────────────────────────────────

const dataAnnotation: Question[] = [
  {
    id: "da1",
    question: "In semantic segmentation, a car's shadow should be labeled as:",
    options: ["Background / ground — a shadow is not part of the car object", "Car — the shadow belongs to the car", "Ambiguous — flag for review", "A separate 'shadow' class regardless of source"],
    correctAnswer: "Background / ground — a shadow is not part of the car object",
    difficulty: "hard",
  },
  {
    id: "da2",
    question: "An audio annotation task requires transcribing speech. The speaker says 'gonna.' The correct transcript is:",
    options: ["Write 'gonna' — transcribe EXACTLY what was spoken", "Write 'going to' — normalize to standard English", "Flag as unclear speech", "Leave blank — colloquial speech should be omitted"],
    correctAnswer: "Write 'gonna' — transcribe EXACTLY what was spoken",
    difficulty: "medium",
  },
  {
    id: "da3",
    question: "A keypoint annotation task requires labeling human pose. An annotator cannot see a person's left elbow (it's behind their back). The correct action is:",
    options: ["Mark the keypoint as 'occluded' at the estimated position", "Skip the left elbow keypoint entirely", "Mirror the right elbow position to estimate the left", "Mark the entire person as unannotatable"],
    correctAnswer: "Mark the keypoint as 'occluded' at the estimated position",
    difficulty: "hard",
  },
  {
    id: "da4",
    question: "A document has a table with 5 columns and 10 rows. For document AI annotation, the table should be labeled as:",
    options: ["A single TABLE region containing all cells", "50 individual CELL regions with no TABLE parent", "5 COLUMN regions and 10 ROW regions", "A FIGURE region — tables are visual elements"],
    correctAnswer: "A single TABLE region containing all cells",
    difficulty: "hard",
  },
  {
    id: "da5",
    question: "An annotation quality audit finds 5% of labels are incorrect. The standard industry minimum accuracy threshold is typically:",
    options: ["95% — 5% error rate is at the borderline minimum threshold", "99% — 5% error rate is unacceptable for production", "90% — 5% error rate is well within standards", "80% — any rate above 80% is publishable"],
    correctAnswer: "95% — 5% error rate is at the borderline minimum threshold",
    difficulty: "hard",
  },
  {
    id: "da6",
    question: "An image shows a dog wearing a hat. The task is to label 'clothing.' The hat should be annotated as:",
    options: ["Clothing — the category is 'clothing' regardless of who wears it", "Animal accessory — distinct from human clothing", "Not annotated — only human clothing is in scope", "Ambiguous — requires a new category definition"],
    correctAnswer: "Clothing — the category is 'clothing' regardless of who wears it",
    difficulty: "hard",
  },
  {
    id: "da7",
    question: "In a relation annotation task, 'Paris is the capital of France.' The correct relation is:",
    options: ["CAPITAL_OF (Paris → France)", "LOCATED_IN (Paris → France)", "PART_OF (Paris → France)", "HAS_CAPITAL (France → Paris)"],
    correctAnswer: "CAPITAL_OF (Paris → France)",
    difficulty: "medium",
  },
  {
    id: "da8",
    question: "A satellite image annotation task requires labeling 'roads.' A forest path wide enough for one person but NOT a vehicle should be labeled as:",
    options: ["Not a road — does not meet the minimum vehicle-width definition", "Road — any path used for travel qualifies", "Trail — a sub-category of road", "Ambiguous — requires project manager decision"],
    correctAnswer: "Not a road — does not meet the minimum vehicle-width definition",
    difficulty: "hard",
  },
  {
    id: "da9",
    question: "Two annotators label sentiment: Annotator A labels 70% as 'Positive', Annotator B labels 40% as 'Positive.' Cohen's Kappa will likely be:",
    options: ["Low — substantial disagreement indicates guideline ambiguity", "High — they agree on 40% of positive labels", "Moderate — average of 70% and 40% is 55%", "Cannot be calculated without seeing all label pairs"],
    correctAnswer: "Low — substantial disagreement indicates guideline ambiguity",
    difficulty: "hard",
  },
  {
    id: "da10",
    question: "An annotation guideline states: 'Label all text in images.' An image has a blurry sign where only 3 of 7 letters are readable. The correct action is:",
    options: ["Annotate the 3 readable letters and mark the rest as illegible '[?]'", "Skip — partially readable text cannot be accurately annotated", "Annotate only if 50% or more of the text is readable", "Annotate the whole word as '[illegible]'"],
    correctAnswer: "Annotate the 3 readable letters and mark the rest as illegible '[?]'",
    difficulty: "hard",
  },
  {
    id: "da11",
    question: "In temporal video annotation, an action starts at frame 45 and ends at frame 72. The annotation should capture:",
    options: ["Frames 45-72 inclusive — both boundary frames are included", "Frames 46-71 — boundary frames are excluded as transitions", "Frame 45 only — the start is the key annotation point", "Frames 44-73 — add 1-frame buffer each side for context"],
    correctAnswer: "Frames 45-72 inclusive — both boundary frames are included",
    difficulty: "medium",
  },
  {
    id: "da12",
    question: "A worker notices the annotation guidelines contain a direct contradiction. The correct action is:",
    options: ["Stop and report the contradiction to the project manager before continuing", "Follow the more lenient interpretation and continue", "Follow the stricter interpretation and continue", "Skip all examples affected by the contradiction"],
    correctAnswer: "Stop and report the contradiction to the project manager before continuing",
    difficulty: "medium",
  },
  {
    id: "da13",
    question: "In named entity annotation, 'the president' (no name given) is:",
    options: ["Not annotated — no specific name means it is not a named entity", "Annotated as PERSON", "Annotated as ROLE / TITLE", "Annotated as ORG"],
    correctAnswer: "Not annotated — no specific name means it is not a named entity",
    difficulty: "hard",
  },
  {
    id: "da14",
    question: "An annotator applies label 'D' to a record in a project with only labels A, B, and C. The annotation tool accepts it. This is:",
    options: ["An annotation error — only defined labels should be applied", "Acceptable — the annotator identified a schema gap", "Useful — novel labels help improve the annotation schema", "Only an error if the project manager did not define label D"],
    correctAnswer: "An annotation error — only defined labels should be applied",
    difficulty: "medium",
  },
  {
    id: "da15",
    question: "An annotator with high throughput (annotations per hour) but a low quality score should be:",
    options: ["Retrained or removed — quality is the primary metric, not speed", "Rewarded for productivity — throughput is the key business metric", "Given easier tasks to compensate for quality gaps", "Flagged only if quality falls below 50%"],
    correctAnswer: "Retrained or removed — quality is the primary metric, not speed",
    difficulty: "medium",
  },
  {
    id: "da16",
    question: "A face detection dataset requires annotating all human faces. An image contains a face on a poster in the background. The poster face should be:",
    options: ["Annotated as 'face-in-image' (non-real) — still a face but with a distinct sub-label", "Annotated the same as real faces", "Not annotated — non-real faces are excluded", "Flagged — project manager must decide case by case"],
    correctAnswer: "Annotated as 'face-in-image' (non-real) — still a face but with a distinct sub-label",
    difficulty: "hard",
  },
  {
    id: "da17",
    question: "An annotation project has the same 200 sentences shared between all 3 annotators. These 200 sentences are used to:",
    options: ["Calculate inter-annotator agreement and calibrate quality", "Serve as additional training examples", "Validate the annotation tool's software accuracy", "Reduce overall project annotation cost"],
    correctAnswer: "Calculate inter-annotator agreement and calibrate quality",
    difficulty: "easy",
  },
  {
    id: "da18",
    question: "For document AI annotation, a document table should be labeled as:",
    options: ["One TABLE region — tables are single entities in document AI", "Individual CELL regions (row × column count)", "Separate HEADER and BODY regions", "A FIGURE — tables are visual, not text, elements"],
    correctAnswer: "One TABLE region — tables are single entities in document AI",
    difficulty: "medium",
  },
  {
    id: "da19",
    question: "In a multi-label annotation task, a single data instance receives labels [A, B, C]. For quality reporting, this instance counts as:",
    options: ["One annotated instance with 3 labels", "Three separate annotation instances", "Invalid — multi-label annotation requires disambiguation", "The most confident label only"],
    correctAnswer: "One annotated instance with 3 labels",
    difficulty: "medium",
  },
  {
    id: "da20",
    question: "An NLP annotation project asks workers to label text as 'formal' or 'informal.' The sentence 'Hey! Can u send me the doc asap?' should be labeled:",
    options: ["Informal", "Formal", "Mixed", "Cannot determine without more context"],
    correctAnswer: "Informal",
    difficulty: "easy",
  },
];

// ── Surveys ────────────────────────────────────────────────────────────────────

const surveys: Question[] = [
  {
    id: "su1",
    question: "A company emails a survey to customers. Only 8% respond. Results show 90% satisfaction. The CORRECT conclusion is:",
    options: ["Results are likely biased — satisfied customers are more likely to respond voluntarily", "90% satisfaction is reliable — absolute response count matters more than rate", "The survey failed — 8% response rate makes results invalid", "Non-respondents are likely even more satisfied"],
    correctAnswer: "Results are likely biased — satisfied customers are more likely to respond voluntarily",
    difficulty: "hard",
  },
  {
    id: "su2",
    question: "A respondent answers 3, 3, 3, 3, 3, 3, 3, 3, 3, 3 for 10 unrelated statements on a 1-5 scale. This most likely suggests:",
    options: ["Central tendency bias — choosing the midpoint to avoid commitment", "Acquiescence bias — agreeing with everything", "Inconsistent responses requiring removal", "Genuine moderate satisfaction across all dimensions"],
    correctAnswer: "Central tendency bias — choosing the midpoint to avoid commitment",
    difficulty: "hard",
  },
  {
    id: "su3",
    question: "A survey of 500 people from a city of 1 million. The margin of error at 95% confidence is approximately:",
    options: ["±4.4%", "±10%", "±0.05%", "±1%"],
    correctAnswer: "±4.4%",
    difficulty: "hard",
  },
  {
    id: "su4",
    question: "A political survey asks: 'Do you support the current government's reckless spending policies?' This question is:",
    options: ["Loaded — 'reckless' is a pejorative that biases the response", "Leading — directly guides toward a yes/no answer", "Double-barreled — asks about government AND spending", "Ambiguous — 'reckless' is undefined"],
    correctAnswer: "Loaded — 'reckless' is a pejorative that biases the response",
    difficulty: "hard",
  },
  {
    id: "su5",
    question: "A researcher conducts the same survey every year with DIFFERENT randomly selected respondents. This is:",
    options: ["Cross-sectional repeated design — not a panel study", "A longitudinal panel study", "A cohort study", "A time-series survey with the same sample"],
    correctAnswer: "Cross-sectional repeated design — not a panel study",
    difficulty: "hard",
  },
  {
    id: "su6",
    question: "An NPS of +47 means:",
    options: ["47% more promoters than detractors", "47% of respondents are promoters", "47 out of 100 respondents gave high scores", "The average score is 4.7 out of 10"],
    correctAnswer: "47% more promoters than detractors",
    difficulty: "hard",
  },
  {
    id: "su7",
    question: "A survey has 30 questions and average completion time is 4 minutes. This suggests:",
    options: ["Many respondents are not reading questions carefully (speeding)", "The survey is efficiently designed", "30 questions in 4 minutes is normal for experienced participants", "The questions are too simple and should be revised"],
    correctAnswer: "Many respondents are not reading questions carefully (speeding)",
    difficulty: "hard",
  },
  {
    id: "su8",
    question: "A mean response of 2.7 on a scale of 1=Never to 5=Always should be reported as:",
    options: ["Between 'Rarely' and 'Sometimes' — do not round to a label", "3 — round to the nearest whole number", "'Sometimes' — the nearest label to 2.7", "Invalid — means of ordinal scales should not be calculated"],
    correctAnswer: "Between 'Rarely' and 'Sometimes' — do not round to a label",
    difficulty: "hard",
  },
  {
    id: "su9",
    question: "Cronbach's Alpha of 0.90 for a 10-item scale indicates:",
    options: ["High internal consistency, but items may be slightly redundant", "Perfect reliability — no issues", "Acceptable but the scale should be revised down to fewer items", "Low validity despite high reliability"],
    correctAnswer: "High internal consistency, but items may be slightly redundant",
    difficulty: "hard",
  },
  {
    id: "su10",
    question: "Respondents skip sensitive questions in an online survey. This data is best treated as:",
    options: ["'Missing At Random' unless there is evidence of systematic patterns", "Imputed with the mean response for that question", "Treated as neutral midpoint responses", "Excluded from analysis entirely"],
    correctAnswer: "'Missing At Random' unless there is evidence of systematic patterns",
    difficulty: "hard",
  },
  {
    id: "su11",
    question: "In a health survey, 'self-reported height' data will most likely:",
    options: ["Overestimate actual height — people tend to round up", "Accurately reflect actual height", "Underestimate actual height — people are modest about their height", "Show no systematic bias"],
    correctAnswer: "Overestimate actual height — people tend to round up",
    difficulty: "hard",
  },
  {
    id: "su12",
    question: "A researcher samples every 10th person from an alphabetical employee list of 10,000. This is:",
    options: ["Systematic sampling", "Simple random sampling", "Cluster sampling", "Stratified sampling"],
    correctAnswer: "Systematic sampling",
    difficulty: "medium",
  },
  {
    id: "su13",
    question: "Factor analysis of a 10-item 'health quality of life' scale reveals 3 distinct factors. This suggests:",
    options: ["The scale measures 3 related but distinct dimensions, not a single construct", "The scale has low validity — one factor was expected", "10 questions is too many — reduce to 3 questions", "The data has 3 outliers that need to be removed"],
    correctAnswer: "The scale measures 3 related but distinct dimensions, not a single construct",
    difficulty: "hard",
  },
  {
    id: "su14",
    question: "An exit poll shows 60% voted for Candidate A. The official count shows Candidate A won with 52%. The MOST likely explanation is:",
    options: ["Differential response — Candidate A's supporters were more willing to disclose their vote", "The exit poll sample size was insufficient", "Voters lied about their votes in the exit poll", "The official count contains counting errors"],
    correctAnswer: "Differential response — Candidate A's supporters were more willing to disclose their vote",
    difficulty: "hard",
  },
  {
    id: "su15",
    question: "A pilot test of a survey with 20 people has the PRIMARY purpose of:",
    options: ["Identifying confusing questions, technical errors, and completion time issues", "Collecting a small preliminary dataset for early analysis", "Testing whether a sample size of 20 is sufficient for the main study", "Validating the survey's construct validity"],
    correctAnswer: "Identifying confusing questions, technical errors, and completion time issues",
    difficulty: "medium",
  },
  {
    id: "su16",
    question: "A survey question: 'How many drinks did you have last week?' primarily suffers from:",
    options: ["Recall bias — respondents may not accurately remember exact consumption", "Social desirability bias only", "Leading question bias", "Coverage bias — excludes non-drinkers"],
    correctAnswer: "Recall bias — respondents may not accurately remember exact consumption",
    difficulty: "medium",
  },
  {
    id: "su17",
    question: "To ensure equal representation of all age groups in a survey, you should use:",
    options: ["Stratified random sampling", "Simple random sampling", "Cluster sampling", "Systematic sampling"],
    correctAnswer: "Stratified random sampling",
    difficulty: "easy",
  },
  {
    id: "su18",
    question: "A survey asks about sensitive income data. To maximize response rate, the income question should be placed:",
    options: ["At the END of the survey", "At the START of the survey", "In the MIDDLE of the survey", "Placement does not affect response rate for sensitive questions"],
    correctAnswer: "At the END of the survey",
    difficulty: "hard",
  },
  {
    id: "su19",
    question: "Double-barreled means a survey question:",
    options: ["Asks about two different things in a single question", "Contains two negatives", "Has two correct answers", "Was used in two different surveys"],
    correctAnswer: "Asks about two different things in a single question",
    difficulty: "easy",
  },
  {
    id: "su20",
    question: "A survey is administered by the manager to measure their own team's satisfaction. This primarily introduces:",
    options: ["Both social desirability bias AND interviewer effect — both compound together", "Only social desirability bias", "Only coverage bias", "No bias if the survey is anonymous"],
    correctAnswer: "Both social desirability bias AND interviewer effect — both compound together",
    difficulty: "hard",
  },
];

// ── Video Analysis ─────────────────────────────────────────────────────────────

const videoAnalysis: Question[] = [
  {
    id: "va1",
    question: "A video titled 'How to hack WiFi passwords' contains only professional network security testing tutorials for administrators. The correct moderation action is:",
    options: ["Keep with a 'Professional Security Content' label — content is legitimate despite misleading title", "Remove — the title violates platform guidelines regardless of content", "Add a warning label only", "Remove only if accessible to under-18 accounts"],
    correctAnswer: "Keep with a 'Professional Security Content' label — content is legitimate despite misleading title",
    difficulty: "hard",
  },
  {
    id: "va2",
    question: "A deepfake detector flags a video as 'likely synthetic' with 78% confidence. The correct action is:",
    options: ["Flag for human review — 78% is significant but below the automatic-removal threshold", "Remove immediately — any probability above 50% triggers removal", "Keep — 22% chance of being real is insufficient justification for removal", "Run a second detection model before deciding"],
    correctAnswer: "Flag for human review — 78% is significant but below the automatic-removal threshold",
    difficulty: "hard",
  },
  {
    id: "va3",
    question: "A video claims '5G towers cause cancer' and includes a disclaimer: 'this is personal opinion.' The disclaimer:",
    options: ["Does NOT protect the video — health misinformation requires removal regardless of disclaimers", "Protects the video — personal opinion is always permitted", "Reduces the severity — keep with a warning label", "Only matters if the video has over 100,000 views"],
    correctAnswer: "Does NOT protect the video — health misinformation requires removal regardless of disclaimers",
    difficulty: "hard",
  },
  {
    id: "va4",
    question: "A documentary about the Holocaust includes actual historical footage of atrocities. This video should be:",
    options: ["Kept — historical educational content is exempt from graphic violence removal policies", "Removed — graphic historical footage violates violence policies regardless of context", "Age-restricted (18+) only", "Kept with a warning overlay, but no restriction needed"],
    correctAnswer: "Kept — historical educational content is exempt from graphic violence removal policies",
    difficulty: "hard",
  },
  {
    id: "va5",
    question: "A video has 500,000 comments. All 200 most recent comments are identical: 'Great video!' from different accounts. This indicates:",
    options: ["Comment spam / bot activity — identical comments from many accounts = inauthentic", "The video is genuinely popular — high identical engagement is expected", "A real fan community using a shared phrase", "A platform bug causing comment duplication"],
    correctAnswer: "Comment spam / bot activity — identical comments from many accounts = inauthentic",
    difficulty: "medium",
  },
  {
    id: "va6",
    question: "A content creator uses a 5-second clip of a copyrighted song in a 10-minute video review of that song. Under fair use principles, this is:",
    options: ["Likely fair use — short clip for commentary/review with transformative intent", "Clear copyright violation — any unlicensed music use is infringement", "Fair use only if the creator earns no revenue from the video", "Depends entirely on the country — fair use is not universal"],
    correctAnswer: "Likely fair use — short clip for commentary/review with transformative intent",
    difficulty: "hard",
  },
  {
    id: "va7",
    question: "A video's auto-generated captions show '[Music]' for 40% of the video. For accessibility assessment, this video:",
    options: ["Fails accessibility standards — non-speech audio must be described, not just labeled", "Passes — '[Music]' is the correct caption for background music", "Partially passes — '[Music]' is acceptable for non-integral background music only", "Cannot be assessed without knowing whether the music is integral to the content"],
    correctAnswer: "Fails accessibility standards — non-speech audio must be described, not just labeled",
    difficulty: "hard",
  },
  {
    id: "va8",
    question: "An influencer posts a product review video for an item received for free but does NOT disclose this. This requires:",
    options: ["Flagging for FTC compliance violation — sponsored content must be disclosed", "No action — disclosure is the creator's legal responsibility, not the platform's", "Removal — undisclosed paid promotion is strictly prohibited", "Action only if money was exchanged, not just free products"],
    correctAnswer: "Flagging for FTC compliance violation — sponsored content must be disclosed",
    difficulty: "hard",
  },
  {
    id: "va9",
    question: "A 30-second clip of a violent movie scene (from a major theatrical release) is uploaded by a user. The correct classification is:",
    options: ["Potentially violating — theatrical content does not transfer copyright permissions to the uploader", "Allowed — content from major studios is always licensed for sharing", "Allowed if the uploader credits the studio in the description", "Only restricted if the original film is rated R or equivalent"],
    correctAnswer: "Potentially violating — theatrical content does not transfer copyright permissions to the uploader",
    difficulty: "hard",
  },
  {
    id: "va10",
    question: "A video thumbnail shows a shocked-expression face, red arrows, and a blurred image. This is an example of:",
    options: ["Clickbait thumbnail — designed to manipulate clicks without accurately representing content", "Acceptable marketing — emotional thumbnails drive legitimate engagement", "Only clickbait if the thumbnail is entirely unrelated to the video", "A standard high-CTR YouTube thumbnail format"],
    correctAnswer: "Clickbait thumbnail — designed to manipulate clicks without accurately representing content",
    difficulty: "medium",
  },
  {
    id: "va11",
    question: "For brand safety classification, a video about the history of Nazi Germany is:",
    options: ["Context-dependent — educational/historical content may be brand-safe with appropriate warnings", "Always brand unsafe — any Nazi content is flagged regardless of educational value", "Always brand safe — educational content is universally acceptable to advertisers", "Brand unsafe only if it appears in pre-roll advertising inventory"],
    correctAnswer: "Context-dependent — educational/historical content may be brand-safe with appropriate warnings",
    difficulty: "hard",
  },
  {
    id: "va12",
    question: "A children's educational video accidentally includes a 2-second clip of adult language. The correct action is:",
    options: ["Edit or remove the offending segment — children's content has stricter standards", "Add a content warning and reclassify to 13+", "Remove the entire video permanently", "No action if the inclusion was accidental"],
    correctAnswer: "Edit or remove the offending segment — children's content has stricter standards",
    difficulty: "medium",
  },
  {
    id: "va13",
    question: "A video generated entirely by an AI tool (no real people) depicts a realistic crime scene. It should be:",
    options: ["Reviewed under the same content policies as live-action content — policy applies to content, not production method", "Exempt — AI-generated content has different content rules", "Auto-approved — no real people means no real harm", "Flagged only for law enforcement, not general moderation"],
    correctAnswer: "Reviewed under the same content policies as live-action content — policy applies to content, not production method",
    difficulty: "hard",
  },
  {
    id: "va14",
    question: "A video of a protest shows police using tear gas. The correct classification is:",
    options: ["Newsworthy civil unrest — keep with a context label, do not remove", "Violence — police force always requires removal", "Political content — restrict to users over 18 only", "Sensitive content — remove pending legal review"],
    correctAnswer: "Newsworthy civil unrest — keep with a context label, do not remove",
    difficulty: "hard",
  },
  {
    id: "va15",
    question: "A video thumbnail reads: 'Lost 30kg in 30 days!' The primary content moderation concern is:",
    options: ["Health misinformation — extreme weight loss claims may be unrealistic and harmful", "Copyright — before/after images may be from other sources", "Only a concern if a product is being sold in the video", "No concern — personal health testimonials are always permitted"],
    correctAnswer: "Health misinformation — extreme weight loss claims may be unrealistic and harmful",
    difficulty: "medium",
  },
  {
    id: "va16",
    question: "A moderation team can review 1,000 videos per day but the AI flags 10,000. The correct prioritization is:",
    options: ["Review highest-confidence AI violation flags first — prioritize likely policy violations", "Review all flags equally — no prioritization to avoid algorithmic bias", "Review the most-viewed videos first regardless of violation type", "Reduce AI sensitivity to lower flag volume to match review capacity"],
    correctAnswer: "Review highest-confidence AI violation flags first — prioritize likely policy violations",
    difficulty: "medium",
  },
  {
    id: "va17",
    question: "A person slips on ice, appears unhurt, and laughs. The video should be classified as:",
    options: ["Safe — unintentional minor accidents with a positive outcome are generally acceptable", "Potentially violating — filming someone without consent applies", "Graphic content requiring a viewer warning", "Depends on the platform's specific 'fail video' policy"],
    correctAnswer: "Safe — unintentional minor accidents with a positive outcome are generally acceptable",
    difficulty: "medium",
  },
  {
    id: "va18",
    question: "A news channel broadcasts live footage of injured survivors from a building fire. The footage should be:",
    options: ["Broadcast with a sensitive content warning — newsworthy events with real harm require viewer preparation", "Removed — footage of injured people is never acceptable on any platform", "Broadcast without restriction — news content has unlimited freedom", "Fully blurred — no injury footage is allowed even in news context"],
    correctAnswer: "Broadcast with a sensitive content warning — newsworthy events with real harm require viewer preparation",
    difficulty: "hard",
  },
  {
    id: "va19",
    question: "A video shows two people arguing loudly on the street with no physical violence. This is classified as:",
    options: ["Conflict content — no policy violation unless physical harm occurs", "Harassment — filming arguments without consent is prohibited", "Violence-adjacent content requiring mandatory review", "Safe content — verbal disputes are normal and never moderated"],
    correctAnswer: "Conflict content — no policy violation unless physical harm occurs",
    difficulty: "medium",
  },
  {
    id: "va20",
    question: "A magic trick video shows a performer appearing to be set on fire. With no additional context, a moderator should:",
    options: ["Investigate context before deciding — professional performance may exempt it from harm policies", "Remove immediately — fire/burning content is always prohibited", "Keep — magic tricks are clearly fictional and never require review", "Age-restrict only — fire content requires a 13+ age gate"],
    correctAnswer: "Investigate context before deciding — professional performance may exempt it from harm policies",
    difficulty: "medium",
  },
];

// ── Exports ────────────────────────────────────────────────────────────────────

export const QUESTION_BANK: Record<string, Question[]> = {
  "Data Categorization": dataCategorization,
  "Text Annotation": textAnnotation,
  "Questionnaires": questionnaires,
  "AI Training Tasks": aiTrainingTasks,
  "Sentence Arrangement": sentenceArrangement,
  "Product Review Analysis": productReviewAnalysis,
  "Data Annotation": dataAnnotation,
  "Surveys": surveys,
  "Video Analysis": videoAnalysis,
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  "Data Categorization": "Classify datasets and documents into the correct data categories using sensitivity hierarchies and classification priority rules.",
  "Text Annotation": "Label text with sentiment, entities, intent, and linguistic features — including edge cases that fool automated systems.",
  "Questionnaires": "Apply survey design methodology: identify bias types, validate scales, and evaluate questionnaire structure.",
  "AI Training Tasks": "Demonstrate knowledge of machine learning data quality, annotation standards, and training dataset requirements.",
  "Sentence Arrangement": "Identify correct logical sequencing, grammatical structure, and document organization in written passages.",
  "Product Review Analysis": "Evaluate review authenticity, detect manipulation patterns, and apply platform moderation standards.",
  "Data Annotation": "Apply annotation principles for images, text, audio, and video — including occlusion handling and quality standards.",
  "Surveys": "Apply survey research methodology: sampling, bias identification, statistical interpretation, and instrument validation.",
  "Video Analysis": "Evaluate video content against platform policies — covering moderation, copyright, accessibility, and safety standards.",
};

export function getRandomQuestions(category: string, count: number): Question[] {
  const pool = QUESTION_BANK[category] ?? [];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
